# Copyright: (c) 2021, Michal Mocnak <michal@narra.eu>, Eric Rosenzveig <eric@narra.eu>
# Copyright: (c) 2021, Narra Project
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

version: '3.8'

services:
  router:
    restart: on-failure
  mongo:
    restart: on-failure
  redis:
    restart: on-failure
  storage:
    restart: on-failure
  api:
    environment:
      - NARRA_ENV=production
    restart: on-failure
  worker:
    environment:
      - NARRA_ENV=production
    restart: on-failure
  worker_node_01:
    environment:
      - NARRA_ENV=production
    restart: on-failure
  editor:
    environment:
      - NARRA_ENV=production
    restart: on-failure
