version: '3.8'
services:
  master:
    volumes:
      - ../../:/narra_source
  worker_alfa:
    volumes:
      - ../../:/narra_source
  worker_bravo:
    volumes:
      - ../../:/narra_source
  editor:
    volumes:
      - ../../:/narra_source
  mongo:
    ports:
      - 27017:27017
