# Copyright: (c) 2021, Michal Mocnak <michal@narra.eu>, Eric Rosenzveig <eric@narra.eu>
# Copyright: (c) 2021, Narra Project
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

version: '3.8'

services:
  router:
    image: traefik:latest
    command:
      - --api=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.network=${NARRA_STACK_NAME}_external
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
    expose:
      - 8080
    networks:
      - external
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.rule=Host(`${NARRA_ROUTER_HOSTNAME}`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080
  mongo:
    image: mongo:latest
    volumes:
      - mongo:/data/db
    networks:
      internal:
        ipv4_address: 172.42.2.2
  redis:
    image: redis:latest
    volumes:
      - redis:/data
    networks:
      internal:
        ipv4_address: 172.42.2.3
  storage:
    image: minio/minio:RELEASE.2020-10-28T08-16-50Z-48-ge773e06e5
    volumes:
      - storage:/data
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    command: server --address :80 /data
    expose:
      - 80
    networks:
      external:
      internal:
        ipv4_address: 172.42.2.4
    labels:
      - traefik.enable=true
      - traefik.http.routers.storage.rule=Host(`${NARRA_STORAGE_HOSTNAME}`)
      - traefik.http.services.storage.loadbalancer.server.port=80
    depends_on:
      - router
  storage_init:
    image: minio/mc:latest
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set storage http://${NARRA_STORAGE_HOSTNAME} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      /usr/bin/mc mb --ignore-existing storage/narra;
      /usr/bin/mc policy set download storage/narra;
      exit 0;
      "
    networks:
      internal:
        ipv4_address: 172.42.2.6
    extra_hosts:
      - "${NARRA_STORAGE_HOSTNAME}: 172.42.2.4"
    depends_on:
      - storage
  api:
    image: phusion/passenger-ruby26
    volumes:
      - logs:/var/log/narra
      - ${NARRA_ROOT}/docker/nginx/api.conf:/etc/nginx/sites-enabled/narra.conf
      - ${NARRA_ROOT}/docker/nginx/env.conf:/etc/nginx/main.d/narra.conf
      - ${NARRA_ROOT}/docker/nginx/upload.conf:/etc/nginx/conf.d/upload.conf
      - ${NARRA_ROOT}/docker/scripts/nginx_service.sh:/etc/service/nginx/run
      - ${NARRA_ROOT}/docker/scripts/api_install.sh:/etc/my_init.d/42_narra_install.sh
      - ${NARRA_ROOT}/docker/scripts/plugins_discovery.sh:/tmp/narra_plugins_discovery.sh
    env_file:
      - ${NARRA_ENV_FILE}
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`${NARRA_API_HOSTNAME}`)
      - traefik.http.services.api.loadbalancer.server.port=80
    expose:
      - 80
    networks:
      external:
      internal:
        ipv4_address: 172.42.2.5
    extra_hosts:
      - "${NARRA_STORAGE_HOSTNAME}: 172.42.2.4"
      - "${NARRA_API_HOSTNAME}: 172.42.2.5"
    depends_on:
      - router
      - mongo
      - redis
      - storage
  editor:
    image: phusion/passenger-ruby26
    volumes:
      - ${NARRA_ROOT}/docker/nginx/editor.conf:/etc/nginx/sites-enabled/narra.conf
      - ${NARRA_ROOT}/docker/nginx/upload.conf:/etc/nginx/conf.d/upload.conf
      - ${NARRA_ROOT}/docker/scripts/nginx_service.sh:/etc/service/nginx/run
      - ${NARRA_ROOT}/docker/scripts/editor_install.sh:/etc/my_init.d/42_narra_install.sh
    env_file:
      - ${NARRA_ENV_FILE}
    labels:
      - traefik.enable=true
      - traefik.http.routers.editor.rule=Host(`${NARRA_EDITOR_HOSTNAME}`)
      - traefik.http.services.editor.loadbalancer.server.port=80
    expose:
      - 80
    networks:
      external:
    depends_on:
      - router
      - api
  worker:
    image: phusion/passenger-ruby26
    volumes:
      - logs:/var/log/narra
      - ${NARRA_ROOT}/docker/scripts/worker_service.sh:/etc/service/narra/run
      - ${NARRA_ROOT}/docker/scripts/worker_install.sh:/etc/my_init.d/42_narra_install.sh
      - ${NARRA_ROOT}/docker/scripts/plugins_discovery.sh:/tmp/narra_plugins_discovery.sh
    env_file:
      - ${NARRA_ENV_FILE}
    environment:
      - NARRA_WORKER_TYPE=master
    networks:
      - internal
    extra_hosts:
      - "${NARRA_STORAGE_HOSTNAME}: 172.42.2.4"
      - "${NARRA_API_HOSTNAME}: 172.42.2.5"
    depends_on:
      - router
      - mongo
      - redis
      - storage
      - api
  worker_node_01:
    image: phusion/passenger-ruby26
    volumes:
      - logs:/var/log/narra
      - ${NARRA_ROOT}/docker/scripts/worker_service.sh:/etc/service/narra/run
      - ${NARRA_ROOT}/docker/scripts/worker_install.sh:/etc/my_init.d/42_narra_install.sh
      - ${NARRA_ROOT}/docker/scripts/plugins_discovery.sh:/tmp/narra_plugins_discovery.sh
    env_file:
      - ${NARRA_ENV_FILE}
    environment:
      - NARRA_WORKER_TYPE=worker
    networks:
      - internal
    extra_hosts:
      - "${NARRA_STORAGE_HOSTNAME}: 172.42.2.4"
      - "${NARRA_API_HOSTNAME}: 172.42.2.5"
    depends_on:
      - router
      - mongo
      - redis
      - storage
      - api
networks:
  external:
    ipam:
      config:
        - subnet: 172.42.1.0/24
  internal:
    ipam:
      config:
        - subnet: 172.42.2.0/24
volumes:
  storage:
  mongo:
  redis:
  logs:

