version: '3.1'
services:
  master:
    environment:
      PASSENGER_APP_ENV: 'development'
      DEBUG: ${DEBUG}
    ports:
      - "1234:1234"
    volumes:
      - ../../:/narra_source
  worker:
    environment:
      PASSENGER_APP_ENV: 'development'
      DEBUG: ${DEBUG}
    ports:
      - "1235:1235"
    volumes:
      - ../../:/narra_source
  mongo:
    ports:
      - "27017:27017"
